src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
src/Equinor.ProCoSys.IPO.WebApi/Program.cs
src/Equinor.ProCoSys.IPO.WebApi/appsettings.Development.json
src/Equinor.ProCoSys.IPO.WebApi/appsettings.QP.json
src/Equinor.ProCoSys.IPO.WebApi/appsettings.Test.json
src/Equinor.ProCoSys.IPO.WebApi/appsettings.json

This means that there is one central place to set all configuration per environment. If a different, local configuration setup is needed, the settings can be exported and stored locally, and Azure App Configuration can be disabled.

Using Azure App Configuration for storing configuration settings.

---

pipelines/api-build.yml
src/Equinor.ProCoSys.IPO.WebApi/Program.cs
src/Equinor.ProCoSys.IPO.WebApi/Startup.cs

Reading Application Insights Instrumentation Key from config instead of writing it to environment variable on deploy.
Changed pipeline to build PR branches and to build and deploy all other branches. Only master branch is automatically triggered.

App insights

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs
src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Invitation.cs
src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/InvitationConfiguration.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20201027113031_AddDescriptionToInvitation.Designer.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20201027113031_AddDescriptionToInvitation.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/CommPkgScopeDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ExternalEmailDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/FunctionalRoleDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQuery.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitationDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/McPkgScopeDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ParticipantDto.cs
src/Equinor.ProCoSys.IPO.Query/PersonDto.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/DeleteAttachment/DeleteAttachmentCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UploadAttachment/UploadAttachmentCommandHandler.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryTests.cs

DevOps#78040
Get invitation endpoint
Persons which become participants through a functional role (use personal email: yes) are now saved with their respective functional role codes in the db. This is to keep track of which persons are under a functional role and which are not.

78040 - Get ipo details

---

src/Equinor.ProCoSys.IPO.MainApi/MainApi/Project/MainApiProjectService.cs

Set includeInstallations = false in order to get only projects, not installations, from webapi. 
Not necessary to add any tests for this. 
DevOps#78850

78850 - No installations in projects list

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs

First instead of single to avoid crash if duplicate participants

Small fix when duplicate participants

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQuery.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/InvitationForMainDto.cs
src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryTests.cs

DevOps#79287
gets invitations by commpkgno (all invitations with given commpkg as scope, or any mcpkg under it). 
currently returns id, title, description, type, status and rowversion. 
Missing M01 & M02 stuff, we need to discuss how to handle this.

79287 get ipo details by comm pkg no

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs
src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Invitation.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20201216114423_DateTimeAndLocationColumnsOnInvitation.Designer.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20201216114423_DateTimeAndLocationColumnsOnInvitation.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitationDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/InvitationForMainDto.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CompletePunchOut/CompletePunchOutCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/DeleteAttachment/DeleteAttachmentCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/SignPunchOut/SignPunchOutCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UploadAttachment/UploadAttachmentCommandHandler.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/InvitationTests.cs
src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Repositories/InvitationRepositoryTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetAttachmentById/GetAttachmentByIdQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetAttachments/GetAttachmentsQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/IPOContextExtension.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Misc/InvitationHelperTests.cs

DevOps#80104
Workaround so that users getting IPO that are not invited to meeting can get all details, except for outlook response.  Add StartTime, EndTime, and Location to IPO db

80104 workaround for if user is not directly invited to fusion meeting

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ParticipantDto.cs
src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/McPkg/MainApiMcPkgServiceTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/IPOContextExtension.cs

DevOps#79573
Added canSign attribute to invitationDto to be used frontEnd to only show sign/compelte/accept buttons to users who are allowed to perform the opertation

79573 CanSign attribute on invitation dto

---

src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/IInvitationValidator.cs
src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs

DevOps#80547
Invitation validator fix. Can send participant with missing email is they have azure oid

80547 Participant validator fix

---

src/Equinor.ProCoSys.IPO.MainApi/MainApi/Project/MainApiProjectService.cs

Add a "hack" so IPO api find the same projects from Main API both on 4.45 and after.
This mean that this change should be merged and put into productinon before releasing next Main API using param includeSubProjectsOnly instead.
PR: https://statoildeveloper.visualstudio.com/Statoil.NextGenProCoSys/_git/ProCoSysWebApi/pullrequest/6024?_a=overview

80635-Rename IncludeInstallations Param

---

src/Equinor.ProCoSys.IPO.WebApi/Dockerfile

The issue has been fixed.
This reverts commit 33e4d2554f3f450694742967305e3b3f02b6ac71.

Revert "Temporarily changed docker sdk image (#78)"

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/MeetingInvitationHelper.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs

DevOps#80726
Consistency in null and none as outlook response. Always return null is person getting meeting does not have access to meeting.

80726 Consistency in outlook response

---

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Invitation.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210215124321_ChangeMaxLengthLocationTitle.Designer.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210215124321_ChangeMaxLengthLocationTitle.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandValidatorTests.cs

- Change max length values as suggested in task [AB#80609](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/80609)

Bug 80609: Text fields too big for outlook

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs

[AB#81124](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81124)
Using logInformation since logTrace has not been configured to show in AI, and this is only temporary.

81124 log fusion response

---

src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CompletePunchOut/CompletePunchOutCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerNegativeTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerTestsBase.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestFactory.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/UserType.cs

[AB#81792](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81792)
**Test cleanup**
Integration tests:
-Removed completor and acceptor - use Signer for all types of signing (including completing and accepting)
-Removed integration tests that are covered in unit tests
-In positive tests such as "complete_invitation_asSigner", I made the getInvitation-requests be done by signer as well, instead of by viewer. For me this makes more sense that it is the signer that is retrieving the IPO before completing. **_LET ME KNOW IF THIS IS WRONG OR DOESNT MAKE SENSE TO YOU._**
Unit tests:
-Added tests to cover validation being done in command handlers (because we are using main API to do some validation)

81792 Integration test cleanup

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs

[AB#81895](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81895)
Throw validation error if the user is adding scope that is not found in main by the GetBy___PkgNos-endpoints. E.g. adding a commpkgno that is not found in GetByCommPkgNos endpoint.
(This bug was discovered when I tried to add a decommissioning pkg as scope. Endpoints in main do not get decommisioning pkgs (this will be changed), so I was able to create an IPO without a scope)

81895 Error if invalid scope

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CancelPunchOut/CancelPunchOutCommandHandler.cs
src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CancelPunchOut/CancelPunchOutCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs

During refactoring. Cancel fusion meeting was accidentally moved to bus receive and call as sync user  instead of call as logged in user.

Moving fusion call from bus receive to direct call pre-save

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs

[AB#81913](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81913)
update participant added duplicate participants of types that could be signer. Fixed.

81913 Duplicate participants bug

---

src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210323093442_AddIndexes.Designer.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210323093442_AddIndexes.cs

[AB#81918](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81918)
Some searches (especially on Johan Castberg in prod) are so slow that we get exception. Possible problem is that we are missing index on some properties. ProjectName feks is always included, so this is perhaps the biggest problem.

81918 Add indexes on properties used in filter

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CompletePunchOut/CompletePunchOutCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UnAcceptPunchOut/UnAcceptPunchOutCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/IInvitationValidator.cs
src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CompletePunchOut/CompletePunchOutCommandValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UnAcceptPunchOut/UnAcceptPunchOutCommandValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandValidatorTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs

[AB#81958](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81958)
Fixed signing bug where contractor and construction company could not perform regular sign. This functionality was wanted from last week, but forgot to change business validator - fixed now.
Small rename. Not "ContractorExists" for example when checking if Completer exists (even if it is a contractor)

81958 fixed signing bug + small rename

---

src/Equinor.ProCoSys.IPO.WebApi/Startup.cs
src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs
src/Equinor.ProCoSys.IPO.WebApi/Synchronization/DisabledServiceBusSender.cs

Adding an empty sender for usage on localhost when all service bus is disabled.
I prefer this over alot of checking inside existing business logic. Open for suggestions.

Adding an empty swallower (developer mode) for service bus messages

---

src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandlerTests.cs

Upon testing the new endpoint I discovered it will still return an invitation as outstanding after it has been accepted. Therefore added a check to filter out accepted IPOs.

82066 -Filter out accepted invitations

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/CommPkgScopeDto.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationById/McPkgScopeDto.cs

Front-end enables/disables the arrows in edit scope based on commpkg- and mcpkg system which has previously never been returned (they have been disabled always until now).
This change does not require changes in any test classes.

81919 - Return commpkg- and mcpkg system in getinvitationbyid

---

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj
src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj
src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
src/Equinor.ProCoSys.IPO.WebApi/Startup.cs
src/Equinor.ProCoSys.IPO.WebApi/appsettings.json

Bug: User received an error msg when creating an IPO saying he couldn't create the invitation, yet still received the invitation in outlook. Turns out this was because Fusion has a retry policy on their post calls, resulting in them creating the outlook invite even after our requests fail. In our code, when our requests fail, we roll back everything we have created and the invitation is never saved to our db. 
To fix this, Fusion added an upgrade to their nuget package allowing us to manually set the request timeout > total timeout, so that their retry never kicks in.

82727 missing ipos timeout bug

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExcelQueryHandler.cs
src/Equinor.ProCoSys.IPO.WebApi/Excel/ExcelConverter.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExportQueryHandlerTests.cs

previously upon export of IPOs you could only see participant and history details if there was only **one** IPO in the search result/export. this code includes the participants sheet also if there are several invitations in the export. 
history sheet should still only be included if there is only one IPO.

85857 - utvidelse av export

---

src/Equinor.ProCoSys.IPO.WebApi/Authentication/AuthenticatorOptions.cs
src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs
src/Equinor.ProCoSys.IPO.WebApi/appsettings.json
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/appsettings.json
src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs

Running IPO Api requires IpoApiObjectId user when saving changes from library topic.
Before complete of PR:
Add sync user to IPO databases (Dev, Test and Prod)
Add Authenticator:IpoApiObjectId to app configuration (Dev, Test and Prod)
After complete of PR:
Remove  from App Configuration (Dev, Test and Prod)
Synchronization:UserOid
Synchronization:Interval

Make sure IPO bus handling uses correct user id

---

src/Equinor.ProCoSys.IPO.Domain/IPlantProvider.cs
src/Equinor.ProCoSys.IPO.Infrastructure/IPOContext.cs
src/Equinor.ProCoSys.IPO.WebApi/Misc/PlantProvider.cs
src/Equinor.ProCoSys.IPO.WebApi/Seeding/SeedingPlantProvider.cs

[AB#88968](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88968)
Don't merge before [AB#88664](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88664) is deployed and verified in prod

88968 - Remove temporary code used in concurrency bugfix

---

src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj

Fusion has fixed a config issue on their end, and it should be safe to update this package now.
Have tested in test that initial nuget upgrading build works in test, so this is just a reversal of my last PR that downgraded Fusion.Integration.
AB#906464

90646 - Upgrade Fusion.Integration to latest version

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs
src/Equinor.ProCoSys.IPO.MainApi/MainApi/CommPkg/ProCoSysCommPkg.cs
src/Equinor.ProCoSys.IPO.MainApi/MainApi/McPkg/ProCoSysMcPkg.cs
src/Equinor.ProCoSys.IPO.Query/GetCommPkgsInProject/GetCommPkgsInProjectQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/GetMcPkgsUnderCommPkgInProjectQueryHandler.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/CommPkg/MainApiCommPkgServiceTests.cs
src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/McPkg/MainApiMcPkgServiceTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Me/MeControllerTestsBase.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTestsBase.cs

Rename SystemPath back to System as this wording needs to be identical to the one in MainApi.
[AB#92505](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/92505)

92505 - Add scope across system - renaming fix

---

src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/FilterDto.cs
src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/FilterDtoValidator.cs

ProjectName is now a required property for /Invitations and /ExportInvitationsToExcel endpoins.
[AB#81893](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81893)

Make projectname required for endpoints

---

src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitations/GetInvitationsQuery.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitations/GetInvitationsQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExcelQueryHandler.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExportQuery.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsQueryBase.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/SortingProperty.cs
src/Equinor.ProCoSys.IPO.WebApi/Authorizations/AccessValidator.cs
src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/FilterDtoValidator.cs
src/Equinor.ProCoSys.IPO.WebApi/Excel/ExcelConverter.cs
src/Equinor.ProCoSys.IPO.WebApi/Misc/ProjectChecker.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsQueries/GetInvitations/GetInvitationsQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExportQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Test.Common/ReadOnlyTestsBase.cs

Changes to make it possible to fetch IPOs across all projects in a plant. 
If null is sent in to endpoints Invitations or ExportInvitationsToExcel, all projects the user has access to in the current plant are included in the query.
[AB#94186](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/94186)

Fetch IPOs across projects.

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CompletePunchOut/CompletePunchOutCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditParticipants/EditParticipantsCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UploadAttachment/UploadAttachmentCommandValidator.cs
src/Equinor.ProCoSys.IPO.Command/PersonCommands/CreatePerson/CreatePersonCommandValidator.cs

After updating FluentValidation we have to specify RuleLevel and ClassLevel CascadeMode. Where we have more than one "RuleFor" we must also specify ClassLevelCascadeMode to keep same validating pattern as before with CascadeMode.Stop.
[AB#94270](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/94270)

94270 - Add ClassLevelCascadeMode where relevant

---

src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandlerTests.cs

Signers should get IPOs that they need to sign even if they are accepted.
[AB#95832](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95832)

95832 - Include accepted IPOs when getting outstanding

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/InvitationHelper.cs

Revert using oid instead of email when creating meeting, as some users use another email than the one connected to their oid
[AB#101227](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/101227)

101227 - Revert using oid instead of email

---

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/PersonAggregate/Person.cs
src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExcelQueryHandler.cs
src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExportQueryHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Test.Common/ReadOnlyTestsBase.cs

Refactored to run a single db-query to fetch all relevant persons in a list of IPOs - instead of querying for a single person in a for-loop. Should better performance and avoid OOM-exception.
[AB#101259](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/101259)

Bug 101259 - Prevent out-of-memory exception in excel-export

---

src/Equinor.ProCoSys.IPO.WebApi/Synchronization/CertificateEventProcessorService.cs

[AB#105637](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105637)
Voided events are resulting in dead letters. Fix until PR for handling voided events is ready.

105637 - Only handle CertificateAccepted events in command

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UpdateRfocAcceptedStatus/UpdateRfocAcceptedCommandHandler.cs
src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/IInvitationRepository.cs
src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/InvitationRepository.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateRfocAccepted/UpdateRfocAcceptedCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Repositories/InvitationRepositoryTests.cs

[AB#107109](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107109)
Error in coding. Should not expect just a single mcpkg when searching for package with mcpkgno, commpkgno, and projectname, since the same mc package can be un multiple IPOs.

107109 - fix error resulting in deadletter

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UpdateRfocAcceptedStatus/UpdateRfocAcceptedCommandHandler.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UpdateRfocVoidedStatus/UpdateRfocVoidedCommandHandler.cs
src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/Certificate/ICertificateApiService.cs
src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/Certificate/MainApiCertificateService.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateRfocAccepted/UpdateRfocAcceptedCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateRfocVoided/UpdateRfocVoidedCommandHandlerTests.cs
src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/Certificate/MainApiCertificateServiceTests.cs

Use Try since endpoint will return NotFound if certificate is voided (or doesnt exist)
[AB#105276](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105276)

105276 - Handle Voided Rfoc - Try on endpoints

---

src/Equinor.ProCoSys.IPO.WebApi/Excel/ExcelConverter.cs

Dates are now displayed in local time in stead of UTC in Excel
[AB#107176](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107176)

Change datetime from UTC to local time in excel report.

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UnAcceptPunchOut/UnAcceptPunchOutCommandHandler.cs
src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandHandler.cs
src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandHandlerTests.cs

[AB#109792](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/109792) 
Getting "sequence contains more than one element" on unaccept and unsign for IPO Admins, since there is more than one participant that matched the criteria. Fixed by also checking that participant row must be signed.

109792 - Unaccept and uncomplete bug for IPO Admins

---

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/FillRfocGuids/FillRfocGuidsCommandHandler.cs
src/Equinor.ProCoSys.IPO.WebApi/Startup.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Persons/PersonsControllerTests.cs
src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestFactory.cs

WithBuilder() Creates a new WebAplicationFactory. This is not needed since we already have an instance. Can call CreateClient directly on that

Fix test factory so it does not create two instances of WAF

---

radixconfig.yaml

Container crashes because the container keeps running out of memory

ci: scale instances

---

SECURITY.md

As per compliance policy for public repo: https://github.com/equinor/it-professional-network/blob/master/doc/SECURITY-template.md

chore: Adding responsible disclosure instructions as per compliance policy
