equinor/procosys-invitation-for-punch-out-api

src/Equinor.ProCoSys.IPO.MainApi/McPkg/IMcPkgApiService.cs, src/Equinor.ProCoSys.IPO.MainApi/McPkg/MainApiMcPkgService.cs, src/Equinor.ProCoSys.IPO.MainApi/McPkg/ProCoSysMcPkg.cs, src/Equinor.ProCoSys.IPO.MainApi/McPkg/ProCoSysMcPkgSearchResult.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsInProject/GetMcPkgsInProjectQuery.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsInProject/GetMcPkgsInProjectQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsInProject/ProCoSysMcPkgDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Scope/ScopeController.cs, src/Equinor.ProCoSys.IPO.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.IPO.WebApi/Permissions.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/CommPkg/MainApiCommPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/McPkg/MainApiMcPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetMcPkgsInProject/GetCommPkgsInProjectQueryTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetMcPkgsInProject/GetMcPkgsInProjectQueryHandlerTests.cs
endpoint to get mc pkgs from main api
=> 77633 get mc pkgs

pipelines/api-build.yml, src/Equinor.ProCoSys.IPO.WebApi/appsettings.json
Changed app settings to make the pipeline work.
=> Fixing pipeline

pipelines/api-build.yml, src/Equinor.ProCoSys.IPO.WebApi/Misc/EnvironmentExtensions.cs, src/Equinor.ProCoSys.IPO.WebApi/Startup.cs
Using test environment in test instead of development.
=> Environments

src/Equinor.ProCoSys.IPO.MainApi/MainApi/McPkg/ProCoSysMcPkg.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/GetMcPkgsInProjectQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/ProCoSysMcPkgDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Scope/ScopeController.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/McPkg/MainApiMcPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetMcPkgsUnderCommPkgInProject/GetMcPkgsByCommPkgNoInProjectQueryHandlerTests.cs
DiscipineCode has been added to getMcPkgs in main API. Get disciplineCode in IPO as well.
=> 78493: Get discipline code on PCS mc pkg

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitationDto.cs
DevOps#79674
createdBy field on IPO so we can display it on the flyout to show who is the organizer
=> 79674 created by name on IPO

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ParticipantDto.cs
=> 79747 added signedAt/By, notes, and attended status on participants

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/MeetingOptions.cs, src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.Domain/IUnitOfWork.cs, src/Equinor.ProCoSys.IPO.Infrastructure/IPOContext.cs, src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj, src/Equinor.ProCoSys.IPO.WebApi/DiModules/ApplicationModule.cs, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerFusionFailsTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs
DevOps#79175
DevOps#78965
Add customized invitation body on outlook invitation. Scope, description, and link to IPO is included.
=> 79175  Add customized invitation body

src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerFusionFailsTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetPersonsWithPrivileges/GetPersonsWithPrivilegesQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetPersonsWithPrivileges/GetPersonsWithPrivilegesQueryTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestFactory.cs
DevOps#80078
Fixed failing tests
=> 80078 fixed failing tests

src/Equinor.ProCoSys.IPO.WebApi/Startup.cs, src/Equinor.ProCoSys.IPO.WebApi/appsettings.json
Could some do a quick check on this, need to redeploy to dev...
=> Adjusting config for bus

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs
=> 80075 Send to group email if usepersonalemail is false

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
DevOps#80107
fixed bug with person and external email in participant if organization = external participant
=> 80107 Bug - personDto and externalDto on participant

src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/InvitationForMainDto.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/IPOContextExtension.cs
DevOps#80151
Add completedAt and acceptedAt fields to response from get invitations by comm pkg no
=> 80151 Add completedAt and acceptedAt fields to response

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs
=> 80200 Fix bug when updating with functional roles

src/Equinor.ProCoSys.IPO.Query/GetAttachmentById/GetAttachmentByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/SignPunchOutDto.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CompletePunchOut/CompletePunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/SignPunchOut/SignPunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/AcceptPunchOutDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/CompletePunchOutDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/ParticipantDtoGet.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/ParticipantToChangeDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/ParticipantToUpdateNoteDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/PersonDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/PersonHelper.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/ParameterCollection.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestFactory.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/UserType.cs
Vol 2 Part 1.... Rest of invitationscontrollertests and invitationscontrollernegativetests
=> 79964 - Rest of invitationscontroller tests

src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/UnitOfWorkTests.cs
=> Added Unit Tests for UnitOfWork

src/Equinor.ProCoSys.IPO.Command/PersonCommands/CreatePerson/CreatePersonCommand.cs, src/Equinor.ProCoSys.IPO.Command/PersonCommands/CreatePerson/CreatePersonCommandHandler.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/PersonAggregate/Person.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/PersonConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210105123644_PersonUsernameAndEmail.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210105123644_PersonUsernameAndEmail.cs, src/Equinor.ProCoSys.IPO.WebApi/Authorizations/ClaimsExtensions.cs, src/Equinor.ProCoSys.IPO.WebApi/Middleware/VerifyOidInDbMiddleware.cs, src/Equinor.ProCoSys.IPO.WebApi/Seeding/Seeder.cs, src/Equinor.ProCoSys.IPO.WebApi/Seeding/Seeders.cs, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/PersonAggregate/PersonTests.cs, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/UnitOfWorkTests.cs, src/tests/Equinor.ProCoSys.IPO.Test.Common/ReadOnlyTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/IPOContextExtension.cs
Added username and email to person.
DevOps#80303
=> Added username and email to person.

src/Equinor.ProCoSys.BusReceiver/BusReceiverTelemetryConstants.cs, src/Equinor.ProCoSys.BusReceiver/Topics/CommPkgTopic.cs, src/Equinor.ProCoSys.BusReceiver/Topics/McPkgTopic.cs, src/Equinor.ProCoSys.BusReceiver/Topics/ProjectTopic.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
Telemetry logging for Topic receive, and removing an irrelevant test
DevOps#80329
=> Telemetry info for bus receiver topics tracking

src/Equinor.ProCoSys.IPO.Command/EventHandlers/HistoryEvents/IpoCanceledEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CancelInvitation/CancelInvitationCommand.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CancelInvitation/CancelInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CancelInvitation/CancelInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/IInvitationValidator.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/HistoryAggregate/EventType.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Invitation.cs, src/Equinor.ProCoSys.IPO.Domain/Events/IpoCanceledEvent.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210112125724_IpoCanceledEvent.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210112125724_IpoCanceledEvent.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/InvitationTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsHelper.cs
=> 79514 Cancel ipo

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/IInvitationValidator.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs
=> 80333 Title must not be unique in project

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CompletePunchOut/CompletePunchOutCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/IpoValidationException.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/SignPunchOut/SignPunchOutCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UpdateAttendedStatusAndNotesOnParticipants/UpdateAttendedStatusAndNotesOnParticipantsCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/IInvitationValidator.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Misc/HttpContextExtension.cs, src/Equinor.ProCoSys.IPO.WebApi/Middleware/GlobalExceptionHandler.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs
=> 80432 Handle exceptions in command handlers

src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Participants/ParticipantsController.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Scope/ScopeController.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTestsHelper.cs
DevOps#80381
Fix routes to start with controller name
=> 80381 Fix routes

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/CommPkg.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/CommPkgConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210120150506_SystemOnCommpkg.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210120150506_SystemOnCommpkg.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/CommPkg/MainApiCommPkgService.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/CommPkg/ProCoSysCommPkg.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/CommPkgTests.cs, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/InvitationTests.cs, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Repositories/InvitationRepositoryTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetLatestMdpIpoStatusOnCommPkgs/GetLatestMdpIpoStatusOnCommPkgsQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/IPOContextExtension.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTestsBase.cs
DevOps#80470
Save system on commpkg in db to ensure that if the user adds new commpkgs, they are on the same subsystem.
Need to wait for main API before merging
=> 80470 Save system on commpkg in db

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
=> 80587 Check person.azureOid for null

src/Equinor.ProCoSys.IPO.WebApi/Dockerfile
Ref https://github.com/NuGet/Announcements/issues/49
Temporarily using a docker image with a fix
=> Temporarily changed docker sdk image

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs
=> 80328 Required was always false because case sensitive email check

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/MeetingInvitationHelper.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
DevOps#80681
Get most "optimistic" response for functional role based on group email and personal emails
=> 80681 Get response on all functional roles

src/Equinor.ProCoSys.IPO.WebApi/Authorizations/ClaimsExtensions.cs
Affiliate tokens don't contain the same claims as internal tokens. Use alternative claims if necessary.
=> Affiliate token

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitationDto.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs
DevOps#80743
canEdit attribute so that Edit-button is only enabled for users who will be able to edit
=> 80743 canEdit attribute on invitation

src/Equinor.ProCoSys.IPO.Query/GetInvitations/GetInvitationsQueryBase.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitations/GetInvitationsQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitations/GetInvitationsQueryHandlerTests.cs
DevOps#80920
Add sorting for type
Add check for length of ipoId before taking substring
Use IEnumerable since we are sorting on a property that gets its value from a method
Added some tests for sorting
=> 80920 Filter and sorting fixes

src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
=> Nuget packages updated for February

src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/PersonConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210217091145_UniqueConstraintOnOid.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20210217091145_UniqueConstraintOnOid.cs
=> 80940 Unique constraint on oid so users are not created twice

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/InvitationHelper.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs
[AB#80968](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/80968)
=> 80968 Add organizer to invitation body

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CancelPunchOut/CancelPunchOutCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandHandler.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/McPkg/IMcPkgApiService.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/McPkg/MainApiMcPkgService.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CancelPunchOut/CancelPunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandHandlerTests.cs
=> Reordering parameter sequence

src/Equinor.ProCoSys.IPO.MainApi/MainApi/CommPkg/MainApiCommPkgService.cs
[AB#81728](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81728)
Include decomissioning packages in comm pkg search
=> 81728 Include decomissioning packages in comm pkg search

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs
[AB#81903](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81903)
=> 81903 Edit with external participant bug

src/Equinor.ProCoSys.IPO.WebApi/Controllers/Participants/ParticipantsController.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Participants/ParticipantsControllerTestsHelper.cs
[AB#81971](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/81971)
=> 81971 Remove endpoints and integration tests for obsolete endpoints

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs
Log participant information when creating an IPO.
=> log participant information when creating an ipo

src/Equinor.ProCoSys.IPO.Command/EventHandlers/PostSaveEvents/BusEventMessage.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/PostSaveEvents/IpoAcceptedEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/PostSaveEvents/IpoCanceledEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/PostSaveEvents/IpoCompletedEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/PostSaveEvents/IpoUnAcceptedEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/PostSaveEvents/IpoUnCompletedEventHandler.cs
Renaming project schema to plant
=> Renaming project schema to plant

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs
Updating nuget package for pcs service bus.
New telemetry constants naming.
=> Updating nuget package

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/IInvitationRepository.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/InvitationRepository.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Repositories/InvitationRepositoryTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
A bad merge in addition to an  incorrect bug fix has been performed approx 1 month ago. Discovered that a lot of functionality was gone without traces.
Re-added it.
=> Re adding lost move commpkg and mcpkg

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs
Logging invitation Id in create ipo and in fusion meeting creation failed exception.
=> Add some more logging for debug purposes

pipelines/api-build.yml
Completes [AB#82752](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/82752)
=> Add Replicas parameter

src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandlerTests.cs
Add nullcheck for person when getting outstanding IPOs
=> Add nullcheck for person when getting outstanding IPOs

pipelines/api-build.yml
Part 1 of leader election functionality. Running leader elector in parallell but no usage of it yet. Verified ok in dev.
=> First steps on our way to leader election functionality

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.WebApi/Startup.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
update bus nuget
fix ipo_libary --> ipo_library typo
add to test
=> 87951 little fixes 

src/Equinor.ProCoSys.IPO.BlobStorage/AzureBlobStorage.cs, src/Equinor.ProCoSys.IPO.Email/EmailService.cs, src/Equinor.ProCoSys.IPO.WebApi/Authentication/Authenticator.cs, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/Equinor.ProCoSys.IPO.WebApi/Program.cs, src/Equinor.ProCoSys.IPO.WebApi/Startup.cs
Added needed middleware and implemented use of IOptionsSnapshot and IOptionsMonitor instead of IOptions.
=> Implement Azure App Config refresh on Sentinel-change.

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/ExternalEmailForCommand.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/FunctionalRoleForCommand.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/ParticipantsForCommand.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/PersonForCommand.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitedPersonDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/ExternalEmailDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/FunctionalRoleDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitedPersonDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/ParticipantDto.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AcceptPunchOut/AcceptPunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CompletePunchOut/CompletePunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/ParticipantsForCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UnAcceptPunchOut/UnAcceptPunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/UnCompletePunchOut/UnCompletePunchOutCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Validators/InvitationValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/PersonDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Me/MeControllerTestsBase.cs
[AB#88613](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88613)
=> 88613 bugfix handling optimistic concurrency hotfix

src/Equinor.ProCoSys.IPO.BlobStorage/Equinor.ProCoSys.IPO.BlobStorage.csproj, src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.Email/Equinor.ProCoSys.IPO.Email.csproj, src/Equinor.ProCoSys.IPO.Infrastructure/Equinor.ProCoSys.IPO.Infrastructure.csproj, src/Equinor.ProCoSys.IPO.MainApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Equinor.ProCoSys.IPO.Command.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/Equinor.ProCoSys.IPO.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Equinor.ProCoSys.IPO.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/Equinor.ProCoSys.IPO.ForeignApi.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Query.Tests/Equinor.ProCoSys.IPO.Query.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Test.Common/Equinor.ProCoSys.IPO.Test.Common.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Equinor.ProCoSys.IPO.WebApi.Tests.csproj
Updatete to latest .Net 5 release (5.0.13)
=> Package update

src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/IInvitationValidator.cs, src/Equinor.ProCoSys.IPO.Command/Validators/InvitationValidators/InvitationValidator.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/EditExternalEmailDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/EditFunctionalRoleDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/EditInvitedPersonDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTests.cs
[AB#88613](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88613)
=> 88613 bugfix handling optimistic concurrency hotfix2

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ExternalEmailDto.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/FunctionalRoleDto.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/FunctionalRolePersonDto.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitedPersonDto.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/ParticipantDto.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationById/GetInvitationByIdQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/CreateInvitation/CreateExternalEmailDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/CreateInvitation/CreateFunctionalRoleDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/CreateInvitation/CreateParticipantsDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/EditInvitation/EditExternalEmailDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/EditInvitation/EditFunctionalRoleDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/EditInvitation/EditInvitedPersonDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/EditInvitation/EditParticipantsDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/GetInvitation/ExternalEmailDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/GetInvitation/FunctionalRoleDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/GetInvitation/FunctionalRolePersonDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/GetInvitation/InvitedPersonDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/GetInvitation/ParticipantDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Me/MeControllerTests.cs
[AB#88613](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88613)
=> 88613 bugfix handling optimistic concurrency - tidy obsolete code

src/Equinor.ProCoSys.IPO.BlobStorage/Equinor.ProCoSys.IPO.BlobStorage.csproj, src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.Email/Equinor.ProCoSys.IPO.Email.csproj, src/Equinor.ProCoSys.IPO.Infrastructure/Equinor.ProCoSys.IPO.Infrastructure.csproj, src/Equinor.ProCoSys.IPO.MainApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj, src/Equinor.ProCoSys.IPO.WebApi/Behaviors/CheckAccessBehavior.cs, src/Equinor.ProCoSys.IPO.WebApi/Behaviors/CheckValidProjectBehavior.cs, src/Equinor.ProCoSys.IPO.WebApi/Behaviors/LoggingBehavior.cs, src/Equinor.ProCoSys.IPO.WebApi/Dockerfile, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Equinor.ProCoSys.IPO.Command.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/Equinor.ProCoSys.IPO.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Equinor.ProCoSys.IPO.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/Equinor.ProCoSys.IPO.ForeignApi.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Query.Tests/Equinor.ProCoSys.IPO.Query.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Test.Common/Equinor.ProCoSys.IPO.Test.Common.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Equinor.ProCoSys.IPO.WebApi.Tests.csproj
[AB#89064](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/89064)
=> 89064 upgrade nuget6.0 - Vol2

src/Equinor.ProCoSys.IPO.BlobStorage/Equinor.ProCoSys.IPO.BlobStorage.csproj, src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.Email/Equinor.ProCoSys.IPO.Email.csproj, src/Equinor.ProCoSys.IPO.Infrastructure/Equinor.ProCoSys.IPO.Infrastructure.csproj, src/Equinor.ProCoSys.IPO.MainApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Equinor.ProCoSys.IPO.Command.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/Equinor.ProCoSys.IPO.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Equinor.ProCoSys.IPO.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/Equinor.ProCoSys.IPO.ForeignApi.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Query.Tests/Equinor.ProCoSys.IPO.Query.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Test.Common/Equinor.ProCoSys.IPO.Test.Common.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Equinor.ProCoSys.IPO.WebApi.Tests.csproj
[AB#90646](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/90646)
=> 90646 - Upgrade all NuGets

src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
Downgrade package to ensure it the cause of error when calling meetings api.
=> 90646 - Downgrade fusion integration package

src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/ExportParticipantDto.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExcelQueryHandler.cs, src/Equinor.ProCoSys.IPO.WebApi/Excel/ExcelConverter.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExportQueryHandlerTests.cs
Add new columns to participant page on export - attended, note, signedby, and signedat
[AB#92434](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/92434)
=> 92434 - Add new columns to excel export

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/CommPkg/ProCoSysCommPkg.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/McPkg/ProCoSysMcPkg.cs, src/Equinor.ProCoSys.IPO.Query/GetCommPkgsInProject/GetCommPkgsInProjectQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/GetMcPkgsUnderCommPkgInProjectQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/CommPkg/MainApiCommPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/McPkg/MainApiMcPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Me/MeControllerTestsBase.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTestsBase.cs
Can create IPO across systems, but not sections
[AB#92505](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/92505)
=> 92505 - Can create IPO across systems

src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandlerTests.cs
Get outstanding IPOs for all signing participants, not just completor and acceptor.
[AB#93399](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/93399)
=> 93399 - Get outstanding IPOs for all signing participants

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
Update Fusion packages and Microsoft.VisualStudio.Azure.Containers.Tols.Targets
[AB#94261](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/94261)
=> 94261 - Update Fusion packages August

src/Equinor.ProCoSys.IPO.Infrastructure/Caching/CacheManager.cs, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Caching/CacheManagerTests.cs
[AB#95260](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95260)
Exact same fix as in pres
=> 95260 improve cache

src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandlerTests.cs
[AB#95709](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95709)
=> 95709 - Call MainApi once to get functional role codes for current user

src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/InvitationConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/ParticipantConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/IPOContext.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20221003204732_AddIndexForInvitationAndParticipant.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20221003204732_AddIndexForInvitationAndParticipant.cs, src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/InvitationDto.cs, src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/ParticipantDto.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandlerTests.cs
Optimized query using projection.
Added two new indexes on Invitations and Participant to support new queries
[AB#95690](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95690)
=> 95690 GetOutstandingIPO optimize query and add index

src/Equinor.ProCoSys.IPO.Infrastructure/IPOContext.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationsByCommPkgNo/GetInvitationsByCommPkgNoQueryHandler.cs
[AB#95840](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95840)
Not sure if we need additional index for this ..
=> 95840 - Improve sql in GetInvitationsByCommPkgNoQueryHandler

src/Equinor.ProCoSys.IPO.Query/GetOutstandingIpos/GetOutstandingIposForCurrentPersonQueryHandler.cs
Set empty list instead of null to avoid NPEs
[AB#96143](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96143)
=> 96143 - Set empty list instead of null

src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/CommPkgConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/InvitationConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/McPkgConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/IPOContext.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20221018100540_3_new_indexes_invitation_mcpkg_commpkg.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20221018100540_3_new_indexes_invitation_mcpkg_commpkg.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs, src/Equinor.ProCoSys.IPO.WebApi/Startup.cs, src/Equinor.ProCoSys.IPO.WebApi/appsettings.json
[AB#96135](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96135)
=> 96135 GetInvitationsByCommPkgNoQueryHandler index and ProjectName required

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CancelPunchOut/CancelPunchOutCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/IpoSendMailException.cs, src/Equinor.ProCoSys.IPO.WebApi/Middleware/GlobalExceptionHandler.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerNegativeTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Invitations/InvitationsControllerTestsHelper.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestsHelper.cs
[AB#96710](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96710)
=> 96710 specify error to client when unable to send mail

src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
[AB#96810](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96810)
=> 96810 - Downgrade ClosedXML to version 0.96.

src/Equinor.ProCoSys.IPO.MainApi/Client/BearerTokenApiClient.cs, src/Equinor.ProCoSys.IPO.MainApi/Client/IBearerTokenApiClient.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/Me/IMeApiService.cs, src/Equinor.ProCoSys.IPO.MainApi/MainApi/Me/MainApiMeService.cs, src/Equinor.ProCoSys.IPO.WebApi/Caches/PermissionCache.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Caches/PermissionCacheTests.cs
[AB#96980](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96980)
=> 96980 - Call Me/TracePlant

src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20221027115038_AddProjectTable.cs
[AB#97717](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/97717)
=> 97717 - Add EXEC statements on Inserts and Updates

src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
[AB#98246](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98246)
=> 98246_add test and fix delete logic

src/Equinor.ProCoSys.IPO.Query/GetLatestMdpIpoStatusOnCommPkgs/GetLatestMdpIpoStatusOnCommPkgsQuery.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetLatestMdpIpoStatusOnCommPkgs/GetLatestMdpIpoStatusOnCommPkgsQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetLatestMdpIpoStatusOnCommPkgs/GetLatestMdpIpoStatusOnCommPkgsQueryTests.cs
[AB#80608](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/80608)
=> 80608 get by comm pkg nos ignore empty commpkgnos

src/Equinor.ProCoSys.IPO.WebApi/DiModules/ApplicationModule.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestFactory.cs
[AB#98917](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98917)
=> 98917 - Added global config for using SplitQuery

src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/Equinor.ProCoSys.IPO.WebApi/Excel/ExcelConverter.cs
Version above 0.96 is incompatible in linux docker installation. Custom Font must be installed. Do this in NuGet upgrade PBI
[AB#100832](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/100832)
=> 100832 - Revert ClosedXML.Excel upgrade

src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/CommPkgTmpTopic.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/LibraryTmpTopic.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/McPkgTmpTopic.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/ProjectTmpTopic.cs
[AB#100990](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/100990)
=> 100990 - Use TmpTopic-classes for deserialize bus messages

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/InvitationHelper.cs
[AB#101215](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/101215)
=> 101215 - use oid as participant identifier as default instead of email

src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
[AB#102918](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/102918)
=> 102918 - Don't TrackEvent for Library types other than "FUNCTIONAL_ROLE"

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
Update Fusion nuget packages.
[AB#104170](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104170)
=> 104170 - update Fusion nuget packages

src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/AttachmentRemovedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/AttachmentUploadedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/AttendedStatusUpdatedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/CommentAddedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/CommentRemovedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoAcceptedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoCanceledEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoCompletedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoCreatedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoEditedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoSignedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoUnSignedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoUnacceptedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/IpoUncompletedEvent.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/NoteUpdatedEvent.cs, src/Equinor.ProCoSys.IPO.ForeignApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsQueryBase.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Misc/CacheController.cs, src/Equinor.ProCoSys.IPO.sln.DotSettings, src/tests/Equinor.ProCoSys.IPO.Command.Tests/EventHandlers/EventDispatcherTests.cs, src/tests/Equinor.ProCoSys.IPO.Test.Common/ReadOnlyTestsBase.cs
[AB#104184](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104184)
=> 104184 latest common

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommand.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/InvitationHelper.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/CreateInvitationDto.cs, src/Equinor.ProCoSys.IPO.WebApi/Controllers/Invitation/InvitationsController.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Authorizations/AccessValidatorTests.cs
Add flag to allow to create online meeting.
[AB#104100](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104100)
=> 104100 - Add possibility for online meeting

src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/CommPkg/ProCoSysCommPkgSearch.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/CommPkg/ProCoSysCommPkgSearchResult.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/CommPkg/ProCoSysSearchCommPkg.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/IMcPkgApiService.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/MainApiMcPkgService.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/ProCoSysMcPkgOnCommPkg.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/GetMcPkgsUnderCommPkgInProjectQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/ProCoSysMcPkgDto.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/CommPkg/MainApiCommPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/McPkg/MainApiMcPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetCommPkgsInProject/GetCommPkgsInProjectQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetMcPkgsUnderCommPkgInProject/GetMcPkgsByCommPkgNoInProjectQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTestsBase.cs
[AB#104516](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104516)
=> 104516 - Different DTOs for different comm/mc endpoints

src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/InvitationDto.cs
[AB#104826](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104826)
=> 104826 - Add isOnline to getInvitation

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/DeletePunchOut/DeletePunchOutCommandValidator.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/DeletePunchOut/DeletePunchOutCommandValidatorTests.cs
[AB#104244](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104244)
=> 104244 - Allow delete on invitation with scope handed over

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Invitation.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationById/GetInvitationByIdQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsQueryBase.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetInvitationsQueries/GetInvitations/GetInvitationsQueryHandlerTests.cs
CanDelete on invitions with scopeHandedOver. Can filter on ScopeHandedOver
[AB#104244](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/104244)
=> 104244 - CanDelete and filter on ScopeHandedOver Ipos

src/Equinor.ProCoSys.IPO.Command/EventHandlers/HistoryEvents/ScopeHandedOverEventHandler.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/HistoryAggregate/EventType.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Invitation.cs, src/Equinor.ProCoSys.IPO.Domain/Events/PreSave/ScopeHandedOverEvent.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/EventHandlers/HistoryEvents/ScopeHandedOverEventHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/AggregateModels/InvitationAggregate/InvitationTests.cs
[AB#105336](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105336) 
Nice to see when status was set
=> 105336 - Add history event for scope handed over

pipelines/api-build.yml
[AB#105863](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105863)
=> 105863 - Use latest of leader elector

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.ForeignApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.Infrastructure/Equinor.ProCoSys.IPO.Infrastructure.csproj, src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Equinor.ProCoSys.IPO.Command.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/Equinor.ProCoSys.IPO.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Equinor.ProCoSys.IPO.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/Equinor.ProCoSys.IPO.ForeignApi.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Query.Tests/Equinor.ProCoSys.IPO.Query.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Test.Common/Equinor.ProCoSys.IPO.Test.Common.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Equinor.ProCoSys.IPO.WebApi.Tests.csproj
[AB#105866](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105866)
=> 105866 Clean up pull requests update nuget

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandHandler.cs
[AB#105907](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105907)
=> 105907 - Add logging for debugging in prod

src/Equinor.ProCoSys.IPO.WebApi/Middleware/CurrentPlantMiddleware.cs
[AB#107302](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107302)
Same fix as for preservation
=> 107302 - Use TryGetValue to get x-plant from Headers

src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/CommPkg/ProCoSysCommPkg.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/CommPkg/ProCoSysSearchCommPkg.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/ProCoSysMcPkg.cs, src/Equinor.ProCoSys.IPO.ForeignApi/MainApi/McPkg/ProCoSysMcPkgOnCommPkg.cs, src/Equinor.ProCoSys.IPO.Query/GetCommPkgsInProject/GetCommPkgsInProjectQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetCommPkgsInProject/ProCoSysCommPkgDto.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/GetMcPkgsUnderCommPkgInProjectQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetMcPkgsUnderCommPkgInProject/ProCoSysMcPkgDto.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/CommPkg/MainApiCommPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/MainApi/McPkg/MainApiMcPkgServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetCommPkgsInProject/GetCommPkgsInProjectQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Query.Tests/GetMcPkgsUnderCommPkgInProject/GetMcPkgsByCommPkgNoInProjectQueryHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ProCoSysCommPkgDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ProCoSysMcPkgDto.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Scope/ScopeControllerTestsBase.cs
[AB#105376](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105376) 
Add RfocSignedAt property on endpoints used to find scope in IPO frontend
=> 105376 - Add RfocSignedAt on dtos

src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.ForeignApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Equinor.ProCoSys.IPO.WebApi.Tests.csproj
[AB#108316](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/108316)
=> 108316 - Update common nuget package to get new email validation

src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsForExport/GetInvitationsForExcelQueryHandler.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitationsQueryBase.cs, src/Equinor.ProCoSys.IPO.WebApi/Excel/ExcelConverter.cs, src/Equinor.ProCoSys.IPO.WebApi/Program.cs
[AB#107057](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107057)
=> 107057: Tuning of queries related to export invitations to Excel.

radixconfig.yaml
[AB#109037](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/109037)
=> Temporarily change memory-setting, to perform tests

src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240124142346_AddStoredProcedureForIPOExport.cs
[AB#110005](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/110005)
=> 110005: Changed CREATE OR ALTER TO CREATE procedure.

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Comment.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/Participant.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/CommentConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/ParticipantConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240502080242_AddGuidToCommentAndParticipant.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240502080242_AddGuidToCommentAndParticipant.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240502094314_AddUniqueConstraintToCommentAndParticipant.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240502094314_AddUniqueConstraintToCommentAndParticipant.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/AddComment/AddCommentCommandHandlerTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandHandlerTests.cs
[AB#112588](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/112588)
=> 112588 Add guids in IPO database for fam transfer

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/CommPkg.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/McPkg.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/CommPkgConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/EntityConfigurations/McPkgConfiguration.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240603134605_AddGuidColumnMcPkgAndCommPkg.Designer.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Migrations/20240603134605_AddGuidColumnMcPkgAndCommPkg.cs
[AB#114009](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/114009)
=> 114009 - Add Guid column to McPkg and CommPkg tables

src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs, src/Equinor.ProCoSys.IPO.Command/Events/CommPkgEvent.cs, src/Equinor.ProCoSys.IPO.Command/Events/CommentEvent.cs, src/Equinor.ProCoSys.IPO.Command/Events/InvitationEvent.cs, src/Equinor.ProCoSys.IPO.Command/Events/McPkgEvent.cs, src/Equinor.ProCoSys.IPO.Command/Events/ParticipantEvent.cs, src/Equinor.ProCoSys.IPO.Fam/SendAllDataToFamCommandHandler.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/CommPkgQuery.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/CommentQuery.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/InvitationQuery.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/McPkgQuery.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/ParticipantQuery.cs, src/Equinor.ProCoSys.IPO.MessageContracts/ICommPkgEventV1.cs, src/Equinor.ProCoSys.IPO.MessageContracts/ICommentEventV1.cs, src/Equinor.ProCoSys.IPO.MessageContracts/IInvitationEventV1.cs, src/Equinor.ProCoSys.IPO.MessageContracts/IMcPkgEventV1.cs, src/Equinor.ProCoSys.IPO.MessageContracts/IParticipantEventV1.cs
[AB#112014](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/112014)
=> 112014 Send data to servicebus for IPO - Fix Dapper error

src/Equinor.ProCoSys.IPO.Fam/FamOptions.cs, src/Equinor.ProCoSys.IPO.Fam/SendAllDataToFamCommandHandler.cs
[AB#112014](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/112014)
=> 112014 Send data to servicebus for IPO - Memory optimization bulk sending

src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/ParticipantAddedEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/EventPublishers/IntegrationEventPublisher.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/ParticipantQuery.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/EventHandlers/IntegrationEvents/ParticipantAddedEventHandlerTest.cs
[AB#115478](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/115478)
=> 115478 Missing participants from IPO to FAM

src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/ParticipantAddedEventHandler.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/ParticipantQuery.cs
[AB#115478](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/115478)
=> 115478 - Missing participants - simplify where clause

src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/Fam/Queries/CommentQuery.cs
[AB#115478](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/115478)
=> 115478 - Missing comments

src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/ParticipantAddedEventHandler.cs, src/Equinor.ProCoSys.IPO.Command/EventHandlers/IntegrationEvents/ParticipantUpdatedEventHandler.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/EventHandlers/IntegrationEvents/ParticipantUpdatedEventHandlerTest.cs
[AB#115478](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/115478)
=> 115478 - Missing participants and comments from IPO to FAM - Fix update participant sending too many rows

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/FillRfocGuids/FillRfocGuidsCommandHandler.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/CommPkg.cs, src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/IInvitationRepository.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Equinor.ProCoSys.IPO.Infrastructure.csproj, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/InvitationRepository.cs, src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitations/GetInvitationsQueryHandler.cs, src/Equinor.ProCoSys.IPO.WebApi/Startup.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/CommPkgEvent.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/StringToDateConverter.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/StringToLongConverter.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/SynchronizationService.cs, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Repositories/InvitationRepositoryTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Persons/PersonsControllerTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/TestFactory.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/StringToDateTimeConverterTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/StringToLongConverterTests.cs
This reverts commit c4e93d266f87df55fccb60492987417dfeb609d4.
The actual fix, which is also reverted du to squash merge being used, will be merged through separate branch.
=> Revert "Bug/115704 ipo for dogger bank a b c is not working (#324)"

src/Equinor.ProCoSys.IPO.Query/GetInvitationsQueries/GetInvitations/GetInvitationsQueryHandler.cs
[AB#115704](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/115704)
=> 115704: Avoid calling main api if roles list is empty.

src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/InvitationRepository.cs
[517](https://github.com/equinor/cc-toolbox/issues/517)
=> GH00517: Also explicitly delete comment objects when deleting invitations

src/Equinor.ProCoSys.IPO.Domain/AggregateModels/InvitationAggregate/IInvitationRepository.cs, src/Equinor.ProCoSys.IPO.Infrastructure/Repositories/InvitationRepository.cs, src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Repositories/InvitationRepositoryTests.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
https://github.com/equinor/cc-toolbox/issues/353
=> GH00353: Dedicated method for updating commpkg description. Simplified parameter check

src/Equinor.ProCoSys.IPO.WebApi/Synchronization/BusReceiverService.cs, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
https://github.com/equinor/cc-toolbox/issues/673
=> GH00673: Not finding project based on guid when processing commpkg topic 

src/Equinor.ProCoSys.IPO.Command/Equinor.ProCoSys.IPO.Command.csproj, src/Equinor.ProCoSys.IPO.Domain/Equinor.ProCoSys.IPO.Domain.csproj, src/Equinor.ProCoSys.IPO.Fam.Tests/Equinor.ProCoSys.IPO.Fam.Tests.csproj, src/Equinor.ProCoSys.IPO.Fam/Equinor.ProCoSys.IPO.Fam.csproj, src/Equinor.ProCoSys.IPO.ForeignApi/Equinor.ProCoSys.IPO.ForeignApi.csproj, src/Equinor.ProCoSys.IPO.Infrastructure/Equinor.ProCoSys.IPO.Infrastructure.csproj, src/Equinor.ProCoSys.IPO.MessageContracts/Equinor.ProCoSys.IPO.MessageContracts.csproj, src/Equinor.ProCoSys.IPO.Query/Equinor.ProCoSys.IPO.Query.csproj, src/Equinor.ProCoSys.IPO.WebApi/Dockerfile, src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/Equinor.ProCoSys.IPO.Command.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Command.Tests/EventHandlers/EventDispatcherTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/EventHandlers/HistoryEvents/AttendedStatusUpdatedEventHandlerTest.cs, src/tests/Equinor.ProCoSys.IPO.Domain.Tests/Equinor.ProCoSys.IPO.Domain.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Infrastructure.Tests/Equinor.ProCoSys.IPO.Infrastructure.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.MainApi.Tests/Equinor.ProCoSys.IPO.ForeignApi.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Query.Tests/Equinor.ProCoSys.IPO.Query.Tests.csproj, src/tests/Equinor.ProCoSys.IPO.Test.Common/Equinor.ProCoSys.IPO.Test.Common.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests/Equinor.ProCoSys.IPO.WebApi.IntegrationTests.csproj, src/tests/Equinor.ProCoSys.IPO.WebApi.Tests/Equinor.ProCoSys.IPO.WebApi.Tests.csproj
https://github.com/equinor/cc-toolbox/issues/599
https://github.com/equinor/cc-toolbox/issues/734
=> 734 and 599 Upgrade to .NET 8 and Snyk fixes

src/Equinor.ProCoSys.IPO.WebApi/Equinor.ProCoSys.IPO.WebApi.csproj
https://github.com/equinor/cc-toolbox/issues/913
=> 913 - Upgrade ClosedXML to fix Snyk vulnerability

src/Equinor.ProCoSys.IPO.Command/ICalendar/CalendarService.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/CreateInvitation/CreateInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandValidator.cs, src/Equinor.ProCoSys.IPO.Command/InvitationCommands/InvitationHelper.cs, src/Equinor.ProCoSys.IPO.Command/StringExtensions.cs, src/Equinor.ProCoSys.IPO.Command/Strings.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/CreateInvitation/CreateInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/InvitationCommands/EditInvitation/EditInvitationCommandValidatorTests.cs, src/tests/Equinor.ProCoSys.IPO.Command.Tests/StringExtensionsTests.cs
https://github.com/equinor/cc-toolbox/issues/1216
=> 1216 - Mail: Use string extension method to strip html

src/Equinor.ProCoSys.IPO.Command/InvitationCommands/EditInvitation/EditInvitationCommandValidator.cs
https://github.com/equinor/cc-toolbox/issues/1216
=> Repair 2 unit tests

.github/workflows/ci-verify-pr-title.yml
Copying over PR title verification pipeline from EOC.
https://github.com/equinor/procosys-export-on-change/blob/1055ce1b73d2e0dfa1bb449662e8e71906313b3e/.github/workflows/ci-verify-pr-title.yml
=> ci: verify pr title workflow

radixconfig.yaml, src/Equinor.ProCoSys.IPO.WebApi/appsettings.json
Moving config out of the App configuration service into the code
=> chore: app config migration
